name: 3D Profile
on:
  schedule:
    - cron: "0 7 * * *"   # diario 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: iHector1
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update 3D profile" || echo "No changes"
          git push
